version: 2
updates:

  # Monitor GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    assignees:
      - "crow50"
    labels:
      - "dependabot"
      - "github-actions"
      - "security"
    allow:
      - dependency-type: "all"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "gha-update"
      include: "scope"


  # Monitor NPM dependencies
  - package-ecosystem: "npm"
    directory: "/portfolio-site"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    assignees:
      - "crow50"
    labels:
      - "dependabot"
      - "dependencies"
      - "npm"
    # Group updates
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "npm-update"
      include: "scope"


  # Monitor Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    assignees:
      - "crow50"
    labels:
      - "dependabot"
      - "dependencies"
      - "docker"
    allow:
      - dependency-type: "all"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "docker-update"
      include: "scope"
