name: Gitleaks Scan

on:
  push:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Fetch all tags and branches
        run: |
          git fetch --prune || true
          git fetch --all --tags
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Uploading SARIF report to GitHub Security tab
      - name: Upload Gitleaks scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'gitleaks-results.sarif'
          category: 'gitleaks-scan'
