name: Gitleaks Scan

on:
  push:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Fetch all tags and branches
        run: |
          git fetch --prune --unshallow || true
          git fetch --all --tags
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --redact --no-banner --report-format json --report-path gitleaks.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: gitleaks-report
          path: gitleaks.json
          retention-days: 7
