name: Gitleaks Scan

on:
  push:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Fetch all tags and branches
        run: |
          git fetch --prune || true
          git fetch --all --tags
      - uses: gitleaks/gitleaks-action@bcfb9cce635345aac9996cedc19b2de8e01b894f # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Uploading SARIF report to GitHub Security tab
      - name: Upload Gitleaks scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@a7afe0a2d717fe23bf93c8d8239d4f43c4a40f02 # v2.27.0
        if: always()
        with:
          sarif_file: 'results.sarif'
          category: 'gitleaks-scan'
