name: Trivy Container Scan

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/.dockerignore'
      - 'portfolio-site/**'
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/.dockerignore'
      - 'portfolio-site/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    # Set permissions for the job to allow uploading SARIF reports
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

        # Building the Docker image to be scanned
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ernest-portfolio:${{ github.sha }} .

        # Scanning the Docker image with Trivy
        # Step will normally fail if CRITICAL or HIGH severity vulnerabilities are found
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ernest-portfolio:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: 'true'
          severity: 'CRITICAL,HIGH'

        # Generating SARIF report with Trivy
      - name: Run Trivy and generate SARIF report
        uses: aquasecurity/trivy-action@0.35.0
        if: always()
        with:
          image-ref: ernest-portfolio:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-container-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          skip-setup-trivy: 'true' # Reuse Trivy binary from the action's cache to speed up setup

        # Uploading SARIF report to GitHub Security tab
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-container-results.sarif'
          category: 'trivy-container-scan'
